version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend
  app:
    container_name: book-store-app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://localhost:27017/book-store
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend
    
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    driver: bridge    
